# Generated by Django 4.2.7 on 2025-07-11 04:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_no', models.CharField(error_messages={'invalid': '社員番号は6桁の数字で入力してください。', 'unique': 'この社員番号は既に使用されています。'}, help_text='6桁の社員番号を入力してください (例: 123456)', max_length=6, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='社員番号は6桁の数字で入力してください。', regex='^\\d{6}$')], verbose_name='社員番号')),
                ('first_name', models.CharField(max_length=30, verbose_name='名前')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('place_work', models.CharField(blank=True, max_length=30, verbose_name='勤務先')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '従業員',
                'verbose_name_plural': '従業員',
                'db_table': 'employee',
                'db_table_comment': '社員情報テーブル',
                'permissions': [('can_access_admin', '관리자 페이지 접근 권한')],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(choices=[('共通', '共通'), ('Techave', 'Techave'), ('H大甕', 'H大甕')], max_length=20, verbose_name='カレンダー名')),
                ('date', models.DateField(verbose_name='日付')),
                ('category', models.CharField(max_length=20, verbose_name='区分')),
            ],
            options={
                'verbose_name': '休日カレンダー',
                'verbose_name_plural': '休日カレンダー一覧',
                'db_table': 'holiday_calendar',
                'unique_together': {('calendar_name', 'date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceMonthly',
            fields=[
                ('monthly_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='個別月日程番号')),
                ('year', models.CharField(max_length=4, verbose_name='年')),
                ('month', models.CharField(max_length=2, verbose_name='月')),
                ('project_name', models.CharField(max_length=100, verbose_name='PJ名')),
                ('base_calendar', models.CharField(max_length=20, verbose_name='基準カレンダー')),
                ('break_minutes', models.PositiveIntegerField(verbose_name='昼休み区分 (分間)')),
                ('standard_work_hours', models.FloatField(verbose_name='基準時間 (Hr)')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='承認済み')),
                ('is_required', models.BooleanField(default=False, verbose_name='承認申請中')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号')),
            ],
            options={
                'verbose_name': '月別勤怠',
                'verbose_name_plural': '月別勤怠',
                'db_table': 'attendance_monthly',
            },
        ),
        migrations.CreateModel(
            name='AttendanceDaily',
            fields=[
                ('daily_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='日付番号')),
                ('date', models.DateField(verbose_name='日付')),
                ('work_type', models.CharField(blank=True, choices=[('出勤', '出勤'), ('有給', '有給'), ('有給(半)', '有給(半)'), ('代休', '代休'), ('振替(休)', '振替(休)'), ('振替(法)', '振替(法)'), ('振替(勤)', '振替(勤)'), ('特別休暇', '特別休暇'), ('欠勤', '欠勤'), ('休日', '休日'), ('休日(法)', '休日(法)'), ('祝日', '祝日'), ('その他', 'その他')], max_length=20, null=True, verbose_name='勤務区分')),
                ('alternative_work_date', models.DateField(blank=True, null=True, verbose_name='代休/振替の勤務日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='作業開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='作業終了時刻')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='実施作業内容/備考')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='確認')),
                ('is_required', models.BooleanField(default=False, verbose_name='承認申請中')),
                ('monthly_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancemonthly', verbose_name='個別月日程番号')),
            ],
            options={
                'verbose_name': '日別勤怠',
                'verbose_name_plural': '日別勤怠',
                'db_table': 'attendance_daily',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年')),
                ('month', models.CharField(max_length=2, verbose_name='月')),
                ('payment', models.PositiveIntegerField(default=0, verbose_name='支給額')),
                ('deduction', models.PositiveIntegerField(default=0, verbose_name='控除額')),
                ('net_payment', models.PositiveIntegerField(default=0, verbose_name='差引支給額')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='備考')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員')),
            ],
            options={
                'verbose_name': '給与明細書',
                'verbose_name_plural': '給与明細書',
                'db_table': 'pay_slip',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaidLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='年')),
                ('total_days', models.PositiveIntegerField(verbose_name='付与日数')),
                ('used_days', models.PositiveIntegerField(default=0, verbose_name='使用日数')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='備考')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員')),
            ],
            options={
                'verbose_name': '有給休暇',
                'verbose_name_plural': '有給休暇',
                'db_table': 'paid_leave',
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.AddConstraint(
            model_name='attendancemonthly',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='unique_monthly_attendance'),
        ),
        migrations.AddConstraint(
            model_name='attendancedaily',
            constraint=models.UniqueConstraint(fields=('monthly_attendance', 'date'), name='unique_daily_attendance'),
        ),
    ]
