# Generated by Django 4.2.7 on 2025-07-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemonthly',
            name='lunch_break_hours',
        ),
        migrations.RemoveField(
            model_name='attendancemonthly',
            name='standard_work_minutes',
        ),
        migrations.AddField(
            model_name='attendancemonthly',
            name='break_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='昼休み区分 (分間)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancemonthly',
            name='standard_work_hours',
            field=models.FloatField(default=1, verbose_name='基準時間 (Hr)'),
            preserve_default=False,
        ),
    ]
