# Generated by Django 4.2.7 on 2025-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendancemonthly_lunch_break_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedaily',
            name='work_type',
            field=models.CharField(blank=True, choices=[('出勤', '出勤'), ('有給', '有給'), ('有給(半)', '有給(半)'), ('代休', '代休'), ('振替', '振替'), ('特別休暇', '特別休暇'), ('欠勤', '欠勤'), ('休日', '休日'), ('休日(法)', '休日(法)'), ('祝日', '祝日'), ('その他', 'その他')], max_length=20, null=True, verbose_name='勤務区分'),
        ),
    ]
